[package]
name = "control-plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
tokio-stream = "0.1"
aws-config = "0.54.1"
aws-sdk-ec2 = "0.24.0"
ssh2 = { version = "0.9.3", features = ["vendored-openssl"] }
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws", "rustls"] }
serde_json = "1.0.88"
reqwest = { version = "0.11.13", features = ["rustls-tls"], default-features = false }
clap = { version = "4.0.29", features = ["derive"] }
whoami = "0.2.0"
async-trait = "0.1.51"
aws-types = "0.54.1"
anyhow = "1.0.69"
serde = "1.0.159"
web3 = "0.19.0"

[profile.release]
lto = true

